version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
        - "5432:5432"
    restart: always
    volumes:
        - ./pgdata:/var/lib/postgresql/data