export const env = {
  NODE_ENV: 'NODE_ENV',
  PLAYGROUND_API_PROD_URL: 'PLAYGROUND_API_PROD_URL',
  PLAYGROUND_API_DEV_URL: 'PLAYGROUND_API_DEV_URL',
  PLAYGROUND_API_DEV_JWT_TOKEN: 'PLAYGROUND_API_DEV_JWT_TOKEN',
  PLAYGROUND_API_PROD_JWT_TOKEN: 'PLAYGROUND_API_PROD_JWT_TOKEN',
  production: 'production',
  development: 'development',
  local: 'local',
};
